### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'geturl'

### ISSUE THREAD

**Issue by matsapura98** [c4software/python-sitemap#75]
I got such error
 python3 main.py --domain https://domain.com --output sitemap.xml

Traceback (most recent call last):
  File "main.py", line 60, in <module>
    crawl.run()
  File "/root/python-sitemap/crawler.py", line 127, in run
    self.__crawl(current_url)
  File "/root/python-sitemap/crawler.py", line 264, in __crawl
    final_url = response.geturl()
AttributeError: 'NoneType' object has no attribute 'geturl'

**Comment by c4software** [comment]
Interesting what is your Python version please ?

**Comment by matsapura98** [comment]
Python 3.8.2

**Comment by ChenKuanSun** [comment]
It is showing  on pdf file url exist.
So content might be not parseable and response will be None.

Need add condition in `final_url = response.geturl()` like 
`final_url = response.geturl() if response is not None else current_url`

**Comment by Pacifist2503** [comment]
> It is showing on pdf file url exist. So content might be not parseable and response will be None.
> 
> Need add condition in `final_url = response.geturl()` like `final_url = response.geturl() if response is not None else current_url`
> 
> I create a PR #77

Please help me figure out in which file exactly which line to insert, what to exclude the specified error?
